kernel: deepgemm_sm100_m_grouped_fp8_gemm_contiguous
configs:
  - {config: g4_m8192_n6144_k7168, default: true}
  - {config: g4_m8192_n7168_k3072, default: true}
  - {config: g4_m8192_n4096_k4096, default: true}
  - {config: g4_m8192_n4096_k2048, default: true}
  - {config: g8_m4096_n6144_k7168, default: true}
  - {config: g8_m4096_n7168_k3072, default: true}
  - {config: g8_m4096_n4096_k4096, default: true}
  - {config: g8_m4096_n4096_k2048, default: true}
  - {config: g4_m8192_n6144_k7168_bfp4, default: true}
  - {config: g8_m4096_n4096_k2048_bfp4, default: true}
  - {config: g4_m8192_n4096_k4096_psum, default: true}
  - {config: g8_m4096_n7168_k3072_psum_zp, default: true}
