kernel: megakernel_moe
configs:
  - {config: moe_a3b_bs1_all, default: true}
  - {config: moe_a3b_bs8_all, default: true}
  - {config: moe_a3b_bs32_all, default: true}
  - {config: moe_a3b_bs128_all, default: true}
  - {config: moe_a3b_bs512_all, default: true}
  - {config: moe_a3b_bs1024_all, default: true}
  - {config: moe_a3b_bs2048_all, default: true}
  - {config: moe_a3b_bs4096_all, default: true}
