kernel: rmsnorm
configs:
  - {config: hs128_bs1, default: false}
  - {config: hs128_bs2, default: false}
  - {config: hs128_bs4, default: false}
  - {config: hs128_bs8, default: false}
  - {config: hs128_bs16, default: false}
  - {config: hs128_bs32, default: false}
  - {config: hs128_bs64, default: false}
  - {config: hs128_bs128, default: false}
  - {config: hs128_bs4113, default: false}
  - {config: hs4096_bs1, default: false}
  - {config: hs4096_bs2, default: false}
  - {config: hs4096_bs4, default: false}
  - {config: hs4096_bs8, default: false}
  - {config: hs4096_bs16, default: false}
  - {config: hs4096_bs32, default: false}
  - {config: hs4096_bs64, default: false}
  - {config: hs4096_bs128, default: false}
  - {config: hs4096_bs4113, default: false}
  - {config: hs5120_bs1, default: false}
  - {config: hs5120_bs2, default: false}
  - {config: hs5120_bs4, default: false}
  - {config: hs5120_bs8, default: false}
  - {config: hs5120_bs16, default: false}
  - {config: hs5120_bs32, default: false}
  - {config: hs5120_bs64, default: false}
  - {config: hs5120_bs128, default: false}
  - {config: hs5120_bs4113, default: false}
  - {config: hs8192_bs1, default: false}
  - {config: hs8192_bs2, default: false}
  - {config: hs8192_bs4, default: false}
  - {config: hs8192_bs8, default: false}
  - {config: hs8192_bs16, default: false}
  - {config: hs8192_bs32, default: false}
  - {config: hs8192_bs64, default: false}
  - {config: hs8192_bs128, default: false}
  - {config: hs8192_bs4113, default: false}
