kernel: deepgemm_sm100_fp8_gemm_1d1d
configs:
  - {config: m4096_n2112_k7168, default: true}
  - {config: m4096_n576_k7168, default: true}
  - {config: m4096_n24576_k1536, default: true}
  - {config: m4096_n32768_k512, default: true}
  - {config: m4096_n7168_k16384, default: true}
  - {config: m4096_n4096_k7168, default: true}
  - {config: m4096_n7168_k2048, default: true}
  - {config: m4096_n4096_k7168_bfp4, default: true}
  - {config: m4096_n24576_k1536_bfp4, default: true}
  - {config: m4096_n7168_k16384_bfp4, default: true}
